### PR TITLE
Remove panel template "Find Templates" section

### PR DESCRIPTION
**Pull request by tadhgboyle**
Since we no longer provide backwards compatibility to panel templates, and very few (if any) people use them, we are removing this section. There are none posted on the namelessmc marketplace at the moment anyways.

### CODE REVIEW

**Comment by Derkades** [comment]
Backporting this to 2.0.x will break panel templates, but I assume that is intentional given the content of this PR :-)

**Comment by tadhgboyle** [comment]
> Backporting this to 2.0.x will break panel templates, but I assume that is intentional given the content of this PR :-)

Exactly!

**Comment by samerton** [comment]
I think if that's the idea, we should add a migration to reset the panel template back to default, otherwise people won't be able to access the panel templates tab to disable their custom template.

**Comment by partydragen** [comment]
>

**Comment by partydragen** [comment]
> I think if that's the idea, we should add a migration to reset the panel template back to default, otherwise people won't be able to access the panel templates tab to disable their custom template.

Panel templates page and functions will still be there, this is only about removing "Find Templates" section

**Comment by samerton** [comment]
Will the removal of the variables in the page PHP file not break any template files referring to them?

**Comment by partydragen** [comment]
> Will the removal of the variables in the page PHP file not break any template files referring to them?

No, All of this is just for the resource listing, the list of template suggestions from NamelessMC website

**Comment by samerton** [comment]
This does seem to be a breaking change for users using custom panel templates - tested and the attached screenshot is the result (white screen).

We'll need the migration or to push this back to 2.1.0

Screenshot 2023-01-17 at 16 56 03

**Comment by tadhgboyle** [comment]
Ah in that case I think pushing to 2.1.0 is fine! Good catch

**Review by partydragen — APPROVED** [review]

**Pull request merged**
