### PR TITLE
V2 click to copy IP

### LINKED ISSUE #1181: v2 - click to copy IP
**What kind of issue is it (Question, Bug, etc.)?** Feature request (with possible PR?).  
**In which version of NamelessMC did it occur (1.x.x)?** v2 pre 4.  
**How would you describe the issue?** Click to copy the IP in the home header.  
**Do you have (relevant) resources about this issue (Logs, pictures, etc.)?** I implemented the functionality for my test installation (see https://forum.naturamc.com).

I would love to make this a configurable option and make a PR out of it. Is there interest for that feature? I would of course try to improve the look.

### PR DESCRIPTION
**Pull request by NiklasEi**
I removed the html from the language files and made the tooltip it's own message. 

In my opinion, it looks the best without an additional button around it. At least it did when I tried different buttons. 

resolves #1181

### CODE REVIEW

**Comment by NiklasEi** [comment]
Is it critical to add the new message to all language files, or does the system fall back to a default file if a message is missing?

**Comment by baxandrei** [comment]
add the new message to all language files

**Comment by NiklasEi** [comment]
Is there anything else I should improve?

**Comment by samerton** [comment]
Thanks for this, I'll merge and then make a small change to shift the HTML to the template :)

**Pull request merged**
