### PR TITLE
Server Compatibility icons on the left side

### PR DESCRIPTION
**Pull request by TeemoCell**
Server Compatibility  iocns on the left side

Looks way more clean.

**Before**
image

**After**
image

### CODE REVIEW

**Comment by Aberdeener** [comment]
I prefer it how it is currently, let's see if anyone else has thoughts

**Comment by partydragen** [comment]
> I prefer it how it is currently, let's see if anyone else has thoughts

agree

**Comment by TeemoCell** [comment]
The icons on the left side looks way more cleaner xD

**Comment by partydragen** [comment]
> The icons on the left side looks way more cleaner xD

Yea i kinda agree more now after i thinked about it

**Comment by Aberdeener** [comment]
Thank you

**Pull request merged**
