### PR TITLE
German updated

### PR DESCRIPTION
**Pull request by Justman10000**

### CODE REVIEW

**Comment by Aberdeener** [comment]
Looks like there’s some issues with the language files. Can you check them out and then fix? Thanks

**Comment by Justman10000** [comment]
> Looks like there’s some issues with the language files.

In what way?

**Comment by Justman10000** [comment]
> Looks like there’s some issues with the language files.

Hat sich erledigt! Seltsam, es kam die Meldung, dass der String nicht existierte!

**Comment by Justman10000** [comment]
> Looks like there’s some issues with the language files.

It's been dealt with! Strange, the message came up that the string did not exist!

**Comment by Aberdeener** [comment]
Thanks!

**Comment by Derkades** [comment]
> Strange, the message came up that the string did not exist!

If you're using pr12, it has been fixed since then

**Pull request merged**
