### PR TITLE
Make Issue Template

### PR DESCRIPTION
**Pull request by PadowYT2**

### CODE REVIEW

**Comment by Derkades** [comment]
Could you enable issues in settings for your fork so we can see what it looks like?

**Comment by PadowYT2** [comment]
kk

**Comment by PadowYT2** [comment]
done

**Comment by samerton** [comment]
Thanks for this!

Screenshot 2021-09-22 at 18 19 42

Would it be able to change these options to the following:

```
2.0.0-pr11
<= 2.0.0-pr10
1.0.21
<= 1.0.20
```

You can see these in our [security policy](https://github.com/NamelessMC/Nameless/security/policy) - this is just for consistency

**Comment by PadowYT2** [comment]
Here it is ^^

**Comment by Aberdeener** [comment]
Thank you

**Pull request merged**
