### PR TITLE
Update

### PR DESCRIPTION
**Pull request by Justman10000**

### CODE REVIEW

**Comment by supercrafter100** [comment]
I feel like this is unnecessary? It gives info about the permission and its **always** a dangerous permission to give. Even if the user is trustworthy it does give them essentially full power over the website.

**Comment by Justman10000** [comment]
> I feel like this is unnecessary? It gives info about the permission and its **always** a dangerous permission to give. Even if the user is trustworthy it does give them essentially full power over the website.

Yes, but if the user is trustworthy, is he abusing his power?

**Comment by partydragen** [comment]
no reason to break all languages term just for a term keywork

**Comment by supercrafter100** [comment]
> Yes, but if the user is trustworthy, is he abusing his power?
I never said they weren't. I'm just saying that the permission is and will always be dangerous to give. No matter if they're trustworthy or not. If they ever end up turning against you they could nuke your entire website in minutes when they've got administration. You should be very aware of this so "it can be dangrous" isn't clear enough if you ask me. It **IS** dangerous!

**Comment by Justman10000** [comment]
> no reason to break all languages term just for a term keywork

?

**Comment by Justman10000** [comment]
> > Yes, but if the user is trustworthy, is he abusing his power?
> 
> I never said they were abusing powers. I'm just saying that the permission is and will always be dangerous to give. No matter if they're trustworthy or not. If they ever end up turning against you they could nuke your entire website in minutes when they've got administration. You should be very aware of this so "it can be dangrous" isn't clear enough if you ask me. It **IS** dangerous!

Hmm, probably true again

**Comment by Justman10000** [comment]
> no reason to break all languages term just for a term keywork

What difference does it make? As long as it is already done and works...

**Comment by Justman10000** [comment]
8f8e5a6 - Better?

**Comment by supercrafter100** [comment]
Well what's wrong with the original one? 😅 I don't really see the point in changing it at all

**Comment by Justman10000** [comment]
> Well what's wrong with the original one? 😅 I don't really see the point in changing it at all

Mine sounds a bit better...

**Comment by Derkades** [comment]
Thank you for contributing. As others have said I agree that this rewording is not any better and not worth forcing re-translation for all languages

**Pull request closed without merging**
