### PR TITLE
Changed author to Website name

### PR DESCRIPTION
**Pull request by partydragen**
Changed all author from Samerton to <?php echo $sitename; ?> on all pages
That solving this problem:
https://github.com/NamelessMC/Nameless/issues/449

I don't want to push this, I want samerton to agree with this
Its sure other better ways to solve this

### CODE REVIEW

**Comment by Cl1608Ho** [comment]
Wait, this isn't in some sort of templating? :o

**Comment by partydragen** [comment]
What

**Comment by Fellings1** [comment]
@samerton Fixed the "Samerton" title of the software.

**Comment by samerton** [comment]
Thanks for this, merging now. This shouldn't be an issue with version 2.0, which will have the author tag in the global header.

**Comment by Fellings1** [comment]
Close

**Pull request merged**
