### PR TITLE
Code cleanup

### PR DESCRIPTION
**Pull request by XYZHolder**

### CODE REVIEW

**Comment by supercrafter100** [comment]
I feel like we don’t need a pr that is the code run through an auto formatter. We already have phpstan to enforce some code styling

**Comment by supercrafter100** [comment]
As seen by phpstan failing, it doesn’t agree 😅

**Comment by supercrafter100** [comment]
Code style check I mean*

**Comment by Derkades** [comment]
We unfortunately can't accept large reformatting PRs, because they are impossible to review (way more work than to just do it ourselves).

**Pull request closed without merging**
