### PR TITLE
German updated

### PR DESCRIPTION
**Pull request by Justman10000**

### CODE REVIEW

**Comment by Aberdeener** [comment]
Thank you

**Comment by Justman10000** [comment]
> 
> 
> Thank you

I want to update the whole german package, which form of address should I use? Du or Sie?

**Comment by Aberdeener** [comment]
I would follow whatever convention is already in place. But informal "Du" seems fine to me!

**Comment by Justman10000** [comment]
Okay, not that I have to rewrite the whole thing then 😅

**Pull request merged**
