### PR TITLE
Edit the Translations section

### PR DESCRIPTION
**Pull request by Fjuro**
Also fixed a typo (discord -> Discord)

### CODE REVIEW

**Comment by Derkades** [comment]
Thank you for the PR, should we merge this right now or when this repository is added to weblate for v2.1 @samerton ?

**Comment by samerton** [comment]
Best wait for 2.1 when the new language system is in place

**Comment by Fjuro** [comment]
This would also be nice to have in README: https://translate.namelessmc.com/widgets/namelessmc/

**Comment by Derkades** [comment]
I've added this to other repositories (like https://github.com/NamelessMC/Nameless-Link) and I'll add it here once the website is on weblate

**Comment by Fjuro** [comment]
I'm closing this since the README was revamped

**Pull request closed without merging**
