### PR TITLE
Use 4 spaces for indent in languages

### PR DESCRIPTION
**Pull request by ViaSnake**
The indentation of the language file contains a mix of tabs and spaces.
This is inconvenient and confusing when translating, so I replace everything with 4 spaces.

Perhaps the mix of tabs and spaces was causing some of the indentations in some language files to go wrong. I fix that too.

*Change*
`modules/Forum/language/.*/forum.php`
`custom/languages/.*/.*.php`

### CODE REVIEW

**Comment by Derkades** [comment]
Thank you for this, I've been wanting to so it for a long time but forgot

**Comment by ViaSnake** [comment]
`Nameless/custom/languages/*` also needs to be unified into two spaces from the tab? If so, I will add commit to this PR.

**Comment by Derkades** [comment]
Can you format it it to 4 spaces for indentation? That seems to be the standard for all other php files. Unfortunately we have no clear style guidelines yet, #1786

**Comment by ViaSnake** [comment]
Ok. Replaced the tab in all language files with 4 spaces.

**Comment by Derkades** [comment]
I'll leave the final decision to @samerton
it should be merged as soon as possible though to prevent conflicts

**Comment by Derkades** [comment]
@samerton conflicts are already accumulating, please have a look at this PR

**Pull request merged**
