### PR TITLE
New Default Panel Template

### PR DESCRIPTION
**Pull request by CqldFire**
Hey guys, finished with a new default panel template!

This template has all the latest changes applied. It looks much better as it is built with SB Admin 2, and I created a dark and light mode switch. A screenshot is posted below. If you want to try it out AND ARE A STAFF MEMBER, create an account on https://nmc-panel.coldfiredzn.com/ and dm me for an admin role.

image
image

To do/known issues:
- [x] HTML editor always uses light theme
- [x] Chart colors are not optimal in dark theme
- [ ] Sidebar dropdown links focus when clicked but when clicked again don't unfocus
- [ ] The sidebar isn't scrollable currently and so depending on the amount of modules installed it can be kinda long.
- [x] Navigating between pages causes white flashing, this may be hard to fix
- [x] Add namelessmc logo to sidebar
- [ ] Add instant loading
- [x] Update to latest Default template changes

Hopefully this is good enough to make it into the software! Thanks, Coldfire

### CODE REVIEW

**Comment by Aberdeener** [comment]
Looks nice, what are some of the small issues?

**Comment by partydragen** [comment]
well there is alot of space between the sidebar navbar buttons with will make the list very big with was already to big with current template when multiple modules are installed

**Comment by CqldFire** [comment]
Known Issues:
1. CK Editor, radio buttons, some select inputs, and the border for the color picker addon don't match dark mode.
2. Sidebar dropdown links focus when clicked but when clicked again don't unfocus
3. The sidebar isn't scrollable currently and so depending on the amount of modules installed it can be kinda long.

I would like everyone's help with fixing these three issues if possible, especially the 3rd one, since that is the biggest. It will definitely be fixed somehow, whether it is making the sidebar scrollable or decreasing padding between links or something else.

**Comment by zJerino** [comment]
it looks very good, if you need help do not hesitate to contact me

**Comment by Derkades** [comment]
Played around with it a bit and it looks very nice. Some feedback:

I'd increase the text contrast (darker gray). Especially for people without perfect eyesight it might be hard to read.
image

Slightly larger font size and less padding for items in the navbar (same amount of padding as submenus)
image

Maybe put the nameless logo here?
image

**Comment by CqldFire** [comment]
Sounds good, will work on changing some of those things. I am also currently working on reducing sidebar padding and making it scrollable. It will take awhile though because I am having to completely recode the collapsed and mobile versions of the sidebar as they are not designed to be scrollable.

**Comment by CqldFire** [comment]
image

This is what it looks like with the nmc logo as the icon (ignore the scrollbar on the sidebar for now xd)
I'm thinking it doesn't match too well with the theme, but what do you all think?

**Comment by Aberdeener** [comment]
Hmmm....
It doesn't look too bad, but I don't think we should "force" branding on people. Hard to say.

**Comment by Aberdeener** [comment]
PSA: I created `custom/panel_templates/Default/includes` folder with `errors.tpl`, `success.tpl` and `update.tpl` so you dont need all that junk at the top and it can be simply included using `{include file='includes/errors.php'}`.
 Suggest you spend 20 mins and do this. Makes it a lot nicer to deal with!

**Comment by Derkades** [comment]
@CqldFire Would you say this is finished enough to be included in the pr8 release?

**Comment by Derkades** [comment]
Can you commit the NamelessMC logo change? I liked it

**Comment by CqldFire** [comment]
Hey, I can commit the nmc logo change, will do later today.

As for the white flashing issue when you switch pages @Derkades, I specifically coded the theme switcher so this wouldn't happen. I will change some code.
I think it is ready to commit to pre-8, let me add in the latest changes to the default template later today.

As for the includes folder aber, will add that later today.

**Comment by Derkades** [comment]
Since pr8 is scheduled to be released tomorrow, I think it's best to target pr9 instead of pr8 for this PR.

**Comment by CqldFire** [comment]
Sounds good. Will request for a merge as soon as I am done, hopefully in a few days, so it can be merged before development on pre-9 really starts.

**Comment by CqldFire** [comment]
I believe I've fixed the white flicker issue on dark mode with the latest commit, @Derkades can you test on your site?

As for the HTML editor issue I've checked that off as well, because the theme switcher is built off js, and there is no way to change the HTML editor theme except with php.

**Pull request merged**
