### PR TITLE
Change naming of HookHandler class properties and methods

### PR DESCRIPTION
**Pull request by tadhgboyle**
PRing so others have a chance to veto or change any language I have used

With so much stuff being named "hook", this class was always a headache to work on.

Now, modules register "events", and can register a "listener" for any registered event.
As well, "hooks" has been renamed to "webhooks" where applicable, though I think splitting webhook management into its own class would be good.

### CODE REVIEW

**Comment by Derkades** [comment]
Maybe change the class name HookHandler to something else as well? EventHandler? Or simply Events?

**Comment by samerton** [comment]
I guess the one thing I'd comment is that these aren't specific to webhooks

One example of an existing implementation is the delete hook (event) - this is used by other modules to hook into when a user gets deleted to ensure all their data is removed from the database

**Comment by samerton** [comment]
... personally I'd keep hooks 😄 

Hooks are something which plugs into a system to extend its functionality, in this case internally

Whereas I'd say webhooks are a way to communicate with an external system

**Comment by Aberdeener** [comment]
Right, so you’d veto the event/listener wording?

**Pull request merged**
