### PR TITLE
Language to Name History

### PR DESCRIPTION
**Pull request by partydragen**
Language to Name History

### CODE REVIEW

**Comment by aycgit** [comment]
U have to edit it in all language files :)

**Comment by partydragen** [comment]
yea i know but idk how to edit all files in one pull request ;/

And idk Samerton want to use it either

**Comment by aycgit** [comment]
@partydragen u go the the branch u have made this change on and u change files there, then they will also show here

I also just found this out :P

**Comment by partydragen** [comment]
Thanks i added it in all languages now :P

**Pull request merged**
