### PR TITLE
V2 modifications

### PR DESCRIPTION
**Pull request by baxandrei**
Change group_html to group_html_lg and now group_html_lg and group_html is used. group_html_lg on profile view and group_html on forum pages. <<< Update profile.php

Updated profile.jpg
-- Updated image size to be same size like others.

Delete profile_fire_resized.jpg
-- Replaced with another one, and photo theme of nether already exists.

Added new custom profile background images from various topics.
-- (9 new images).

Update texture.png
-- Update texture and size to be same like other files.

Add new 2 custom banners.
-- Added 2 new custom banners with forest and ender in cave for minecraft server status generated image.

### CODE REVIEW

**Comment by Derkades** [comment]
What are the new banners licensed under? I remember seeing the first picture on reddit.

**Comment by baxandrei** [comment]
Uh, I need a license? I found them for free on the internet and I thought I did not need a license for pictures.

**Comment by baxandrei** [comment]
I checked the pages where I downloaded each image and there is no license related text.

**Comment by Derkades** [comment]
No license means full copyright for the owner. Pictures included in this project need to be licenced under a license that allows redistribution and use by for-profit companies. (e.g. MIT or https://creativecommons.org/licenses/by/4.0/)

**Comment by baxandrei** [comment]
Ok. Thanx, i will close this PR and send another only with profile.php

**Comment by Derkades** [comment]
You can also just remove the profile pictures from the existing branch :)

**Pull request closed without merging**
