### PR TITLE
updated Dutch translation

### PR DESCRIPTION
**Pull request by DoraKlikOpDora**
Removed and fixed some strange-formulated sentences, grammar-mistakes and other typo's

### CODE REVIEW

**Comment by DoraKlikOpDora** [comment]
@dangerORclose I have some other words English as well, because it is my opinion that it is 'better' to keep some words English. User is a well-known word and everybody knows what it means. I think UserCP should not be translated because it is a kind of thing of the software, just like you not call MineCraft something like mijnvak.

**Comment by dangerORclose** [comment]
Owkay thats what i tought too.
But anyways MineCraft stays minecraft whatever language it is.. Maybe not for Chinese but they are just special.

**Comment by DoraKlikOpDora** [comment]
@dangerORclose Couldn't come up with a better example. Blame my creativity

**Comment by samerton** [comment]
Thanks!

**Pull request merged**
