### PR TITLE
Add login system by ajax

### PR DESCRIPTION
**Pull request by zJerino**
Demo in https://dev.cuberico.xyz/login/
Username: demo
Password: 123456

### CODE REVIEW

**Comment by Aberdeener** [comment]
Does this need any editing of DefaultRevamp or other 3rd party templates to work?

**Comment by zJerino** [comment]
> Does this need any editing of DefaultRevamp or other 3rd party templates to work?

Non-ajax mode is maintained, but if you want to use ajax there must be an input called ajax with the value "true" for it to work, my template has a function defined in javascript that sends the request

I could make an example script for everything if you want

**Comment by Aberdeener** [comment]
Yes please do that! It would be helpful for template authors to see.

**Comment by zJerino** [comment]
This example works in defaultrevamp:
`{include file='header.tpl'}
{include file='navbar.tpl'}

<h2 class="ui header">
  {$SIGN_IN}
</h2>

{if count($ERROR)}
  <div class="ui error icon message">
    <i class="x icon"></i>
    <div class="content">
      <div class="header">{$ERROR_TITLE}</div>
      <ul class="list">
        {foreach from=$ERROR item=error}
          <li>{$error}</li>
        {/foreach}
      </ul>
    </div>
  </div>
{/if}

<div class="ui padded segment" id="login">
  <div class="ui stackable grid">
    <div class="ui centered row">
      <div class="ui sixteen wide tablet ten wide computer column">
        <form class="ui form" action="" method="post" id="form-login">
          {if isset($EMAIL)}
            <div class="field">
              <label>{$EMAIL}</label>
              <input type="email" name="email" id="email" value="{$USERNAME_INPUT}" placeholder="{$EMAIL}" tabindex="1">
            </div>
          {else}
            <div class="field">
              <label>{$USERNAME}</label>
              <input type="text" name="username" id="username" value="{$USERNAME_INPUT}" placeholder="{$USERNAME}" tabindex="1">
            </div>
          {/if}
          <div class="field">
            <label>{$PASSWORD}</label>
            <input type="password" name="password" id="password" placeholder="{$PASSWORD}" tabindex="2">
          </div>
          <div class="inline field">
            <div class="ui checkbox">
              <input type="checkbox" name="remember" id="remember" value="1" tabindex="3">
              <label for="remember">{$REMEMBER_ME}</label>
            </div>
          </div>
          {if isset($RECAPTCHA)}
            <div class="field">
              <div class="{$CAPTCHA_CLASS}" data-sitekey="{$RECAPTCHA}" tabindex="4"></div>
            </div>
          {/if}
          <input type="hidden" name="token" value="{$FORM_TOKEN}">
          <button type="button" id="clicklogin" class="ui primary button" tabindex="5" onclick="Login()">{$SIGN_IN}</button>
          <a class="ui negative button right floated" href="{$FORGOT_PASSWORD_URL}">{$FORGOT_PASSWORD}</a>
        </form>
        <div class="ui horizontal divider">{$NOT_REGISTERED_YET}</div>
        <div class="ui center aligned">
          <a class="ui large positive button" href="{$REGISTER_URL}">{$REGISTER}</a>
        </div>
      </div>
    </div>
  </div>
</div>



<script>
  function Login() {
     document.querySelector('#clicklogin').classList.add('disabled');
     $.ajax({
         url: siteURL + "logout/"
     })

     $.ajax({
         url: siteURL + "login/",
         type: "POST",
         dataType: "form",
         data: {
             token: $('[name="token"]')[0].value,
             {if (isset($EMAIL))}
                 email: $('[name="email"]')[0].value,
             {else}
                 username: $('[name="username"]')[0].value,
             {/if}
             password: $('[name="password"]')[0].value,
             remember: $('[name="remember"]')[0].value,
             ajax: "true",
         },
         success: 'OK',
     }).catch((req) => {
         document.querySelector('#clicklogin').innerHTML = "{$LOADING}";
         var res = JSON.parse(req.responseText);
         if (res.approved == "true") {
             document.querySelector('#clicklogin').classList.replace('primary', 'positive');
             document.querySelector('#clicklogin').innerHTML = "<i class='check icon'></i>";
             toastr.success(res.message);
             setTimeout(() => {
                 window.location.href = res.url;
             }, 2500)
         } else {
             document.querySelector('#clicklogin').classList.replace('primary', 'negative');
             document.querySelector('#clicklogin').innerHTML = "<i class='times icon'></i>";
             toastr.error(res.message);
             setTimeout(() => {
                 document.querySelector('#clicklogin').classList.replace('negative', 'primary');
                 document.querySelector('#clicklogin').innerHTML = "{$SIGN_IN}";
                 setTimeout(() => {
                     document.querySelector('#clicklogin').classList.remove('disabled');
                 }, 2500)
             }, 2500)
         }
     })
 }
</script>

{include file='footer.tpl'}
`

**Comment by samerton** [comment]
Would it make more sense for there to be a login API endpoint instead?

Just seems a bit odd to bake this functionality into a page instead 😄

**Review by CyberFlameGO — APPROVED** [review]
LGTM

**Comment by Aberdeener** [comment]
> Would it make more sense for there to be a login API endpoint instead?
> 
> Just seems a bit odd to bake this functionality into a page when nothing else works with ajax 😄

Any update on this, @zJerino?

**Pull request closed without merging**
