### PR TITLE
Added Greek Language for Admin

### PR DESCRIPTION
**Pull request by Ar1sC**
Added Greek Language for Admin.php. I will make small changes again. I will update the other files soon.

### CODE REVIEW

**Comment by samerton** [comment]
Thanks for this @Ar1sC! Would you like me to merge these changes now, or wait until the remaining files are translated?

**Comment by Ar1sC** [comment]
@samerton I will translate the remaining files.

**Comment by Derkades** [comment]
Any updates on this @samerton ? I think it's ready to be merged.

**Comment by Ar1sC** [comment]
@samerton  You can merge these changes for now, I will update the other files when I'll have time.

**Comment by samerton** [comment]
@Ar1sC I'll merge now, thanks again :)

**Pull request merged**
