### PR TITLE
[Addons] Core Protect 2 Web Interface & Bungee Admin Tools Web Interface

### PR DESCRIPTION
**Pull request by MuhsinunCool**
Title says it all. Core Protect 2 Web Interface & Bungee Admin Tools Web Interface addons. I themed them to look like NamelessMC. Don't worry, the original creators of the projects are still given credit. <3 :O :D

I'm planning to add support for auto theme switching for them so that they read the database and automatically switch their themes when the main NamelessMC forums theme is switched. <3 :O :D

The main reason I themed the CP2 Web Interface was because I used it on my NamelessMC setup and I just wanted continuity throughout my website so I themed the Core Protect 2 Web Interface to match the Yeti theme that I use on my NamelessMC forums.

The main reason I themed the Bungee Admin Tools Web Interface was because I saw someone in one of the issues for NamelessMC comment how ugly the BATWI was and that was the reason why they didn't want to use it. So I decided to theme it myself and create an addon for NMC that explains how to set it up. Enjoy! <3 :O :D

Screenshots:
Core Protect 2 Web Interface:
image
image
image

Bungee Admin Tools Web Interface:
image
image
image
image

### CODE REVIEW

**Comment by Fellings1** [comment]
@samerton Check this out.

**Comment by samerton** [comment]
I'll double check licenses etc and give everything a run-through before merging, thanks for this though!

**Comment by MuhsinunCool** [comment]
alr tysm! I worked really hard on these :O :D
For copyright, CP2 had SimonOrj's copyright was just his name and his OG GitHub repo at the bottom of the page, which I kept.
BAT only had one thing; it was in the footer. It said please keep it and I didn't want to be an asshole so I didn't remove it; I just made it prettier :P It's a link to the spigot page for his BAT plugin.
Also, how do u check if a player is admin on the forums, and if they are, display the page, and if not, take them back to the home page on the forums? And how do I grab the navbar template?! I could NOT do that. I have a feeling it has something to do with ur pages having to be in the pages directory of NMC, but that stopped CP2 from working so I didn't do it. If u cud change the navbar to auto grab the navbar from the forums, please do so! <3 :D

**Comment by Fellings1** [comment]
@MuhsinunCool Make sure to confirm with us that you have the files updated and there are no reported issues after testing.

**Comment by MuhsinunCool** [comment]
Yes, @Fellings1 they're all ready to be merged thanks!

**Comment by MuhsinunCool** [comment]
Bump, everything is ready to be merged! :D

**Comment by Fellings1** [comment]
@samerton Any details on this?

**Comment by samerton** [comment]
Sorry for the delay, been super busy recently but I'll hopefully get a chance to go through everything after this week.

**Comment by MuhsinunCool** [comment]
Bump

**Comment by MuhsinunCool** [comment]
Bump @samerton @Awtra

**Comment by Derkades** [comment]
You should go through this and change 'u' to 'you', remove ':O :D' after sentences etc.

**Comment by MuhsinunCool** [comment]
@Derkades are you talking about in my post or in the code?

**Comment by Derkades** [comment]
In the code

**Comment by Awtra** [comment]
Just wondering if there was any extra work being done on this @MuhsinunCool . If not maybe @samerton Will be done with this and we can possibly merge this.

**Comment by MuhsinunCool** [comment]
@Awtra I don't currently have the time to work on any projects atm due to school & such. The SAT is coming up and I need to be ready for that. Sorry. Feel free to merge and make any changes to the code you like. It would be preferable if my name would be kept in the copyright of the code. <3 Enjoy

**Comment by SupremeNL** [comment]
Can u add a Cloudflare dashboard? (API)

**Comment by MuhsinunCool** [comment]
@SupremeNL What exactly do you mean by a Cloudflare dashboard? What exactly would this dashboard do?

**Comment by Derkades** [comment]
I think you should publish this as a separate addon, and possibly add it to https://github.com/NamelessMC/Nameless/wiki/Nameless-1.0.x-Modules

**Comment by MuhsinunCool** [comment]
@Derkades I see that they're both already there, however, they're being directed to my SpigotMC resource. I recommend that they link to my GitHub repo so that the user gets the latest version. There are links to my SpigotMC resources in my GitHub repo's README.md files.

**Comment by samerton** [comment]
Sorry it's taken so long to get back to you. 

I really like these modules, however as they're possibly more specific than the current generalised addons present in Nameless, I personally believe the choice should be left to the user in deciding whether they'd like to install these modules. Also, merging these addons into the main repo would make things like new feature additions/module maintenance a bit harder for you, as every change would need to go through a pull request and so on.

For those reasons I'll close this PR, however I have updated the links on the module page to your GitHub repos instead of the Spigot resources, and hopefully once the resources section is ready on the official website you could possibly upload these modules onto there.

**Pull request closed without merging**
