### PR TITLE
:fire: Remove support for custom panel templates

### PR DESCRIPTION
**Pull request by tadhgboyle**
We have talked internally about this change, and decided unanimously that it is worth it.
- Very few (if any) users are using custom panel templates
- None of the 4 panel templates on namelessmc.com have been updated for even pre13

**The biggest reason is that removing custom panel template support means we can make changes to the panel template in a minor release, since we will not have to worry about breaking other custom panel templates. This will allow us to release updates to site configuration faster and more often!**

Requires https://github.com/NamelessMC/debug.namelessmc.com/pull/175

### CODE REVIEW

**Comment by DominikSLK** [comment]
😶

**Review by samerton — DISMISSED** [review]

**Review by PadowYT2 — DISMISSED** [review]
Why should be this done by the context below
Noir - repo was deleted by Teemo
Argon - I'm lazy :smile:
Greendy - Nuke has a lot of problems irl
Dark_Blue - outdated & Viper left NMC

**Review by supercrafter100 — DISMISSED** [review]

**Comment by Aberdeener** [comment]
A good alternate proposal from @partydragen is to display a warning in StaffCP that panel templates have no compatibility promise.
I will change this PR to add this alert instead of fully removing the feature. This way it's a win-win!

**Comment by DominikSLK** [comment]
> A good alternate proposal from @partydragen is to display a warning in StaffCP that panel templates have no compatibility promise.
> I will change this PR to add this alert instead of fully removing the feature. This way it's a win-win!

yes :tada:

**Pull request closed without merging**
