### PR TITLE
Fix custom icons in navbar

### PR DESCRIPTION
**Pull request by partydragen**

### CODE REVIEW

**Comment by mentimjojo** [comment]
This will not fix the icons, it will only add icons as text to the navbar.

**Comment by partydragen** [comment]
Nopp its working its like samertons https://github.com/NamelessMC/Nameless/commit/beea8ef9ad55f5208b5a091f3fbb01d52d4d6bff
Check that commit u see its like and its working ;P

**Comment by mentimjojo** [comment]
I saw that, but when doing it like you are now  you get a plain text.

**Comment by mentimjojo** [comment]
look i know my programming language

**Comment by partydragen** [comment]
We write  class="" in language.php file and working 
	// Icons - will display before the text
	'home_icon' => '<i class="fa fa-cube"></i> ',
	'play_icon' => '<i class="fa fa-gamepad"></i> ',
	'forum_icon' => '<i class="fa fa-comments"></i> ',
	'staff_apps_icon' => '<i class="fa fa-book"></i> '

But i understand what u mean and it working too but if u fix <i class=""> instant u need to edit all addons again and navbar an modules

**Comment by mentimjojo** [comment]
I know that, but it's better and cleaner then html in an language file :package:

**Comment by partydragen** [comment]
Sure Both work we can see that samerton want

**Comment by samerton** [comment]
Thanks, I've pushed my local files which I forgot to include previously now.

**Pull request closed without merging**
