### PR TITLE
Make bold number consistent in player online

### PR DESCRIPTION
**Pull request by Govindass**
I noticed a really weird thing today - the server online player count is bold only when there's more than 1 player online, but when it's only 1 online, it's not bold, so I thought it'll be better to make it bold.

### CODE REVIEW

**Comment by Derkades** [comment]
Thank you for your contribution. To avoid inconsistencies, would you mind updating this for all language files?

**Comment by Govindass** [comment]
> 
> 
> Thank you for your contribution. To avoid inconsistencies, would you mind updating this for all language files?

done

**Comment by Aberdeener** [comment]
Thanks!

**Comment by Derkades** [comment]
A few languages are still missing, I can add those myself though

**Pull request merged**
