### PR TITLE
Update infractions.php

### PR DESCRIPTION
**Pull request by dasilvaj4**
Add support Ban Management offline players

### CODE REVIEW

**Comment by AlliedCore** [comment]
In the aspect of offline ban management do you mean banning players when they are offline or being able to manage banned players while offline?

**Comment by dasilvaj4** [comment]
no, my server is offline mode

**Comment by AlliedCore** [comment]
@dasilvaj4  that makes sense. I think there is a way to make a port extension in order to show a live display of the offline server

**Comment by samerton** [comment]
Thanks for this

**Pull request merged**
