### PR TITLE
Manually Updated Lines 1~252 for Language zh_TW

### PR DESCRIPTION
**Pull request by ichenglin**
I manually read through lines 1 to 252 and updated some sentences to make them read more naturally, and also replaced some incorrectly used punctuations.

Example:
- "." is not a valid period punctuation, instead it should be replaced with "。"

Disclaimer:
- I only edited lines 1~252, this means that any lines after remains unchanged, which still includes incorrect punctuations.

### CODE REVIEW

**Comment by Aberdeener** [comment]
@Dreta hi dreta, can you review this?

**Comment by ichenglin** [comment]
Just realized I accidently removed the "r" from "server" in line 238, it was not part of my translation.

image

**Review by PadowYT2 — CHANGES_REQUESTED** [review]
This should not be done at all, weblate could run into issues. You **must** translate https://translate.namelessmc.com

**Comment by Aberdeener** [comment]
Manual changes to the files is fine Padow, but yep Weblate is a nicer
experience for the translator - not a requirement.

**Comment by ichenglin** [comment]
I did checked the Weblate link before I begin translating, however I still prefer direct file edits over Weblate. Translated strings could easily be compared around to be written in the same style, plus the script editor I am using provide an efficient way of replacing the incorrect punctuations.

**Review by Dreta — APPROVED** [review]
I don’t think there’s a problem with this.

**Comment by Derkades** [comment]
Weblate is configured to wait 48 hours before committing changes. As long as no changes have been made to the language in the last 48 hours, it should be fine

**Comment by ichenglin** [comment]
Fixed the typo of "serve" to "server" in commit 38af18f.

**Comment by Derkades** [comment]
Thanks! Even though you said you weren't finished yet I have already merged this for now, just to avoid any future conflicts.

**Pull request merged**
