### PR TITLE
Bye switchery teemo

### PR DESCRIPTION
**Pull request by TeemoCell**
#2633

### CODE REVIEW

**Comment by supercrafter100** [comment]
Is this related to #2633

**Comment by Derkades** [comment]
Hey, thanks for finishing so many more switches! I'll merge this PR to my branch, I see there's still a few things to fix

**Comment by Derkades** [comment]
Hey, thanks for finishing so many more switches! I'll merge this PR to my branch, I see there's still a few things to fix

**Comment by TeemoCell** [comment]
Iw ill keep the PR open and commit now changes. Lemme know if there is anything to fix.

**Pull request merged**
