### PR TITLE
Fix upgrade script by removing switch

### PR DESCRIPTION
**Pull request by smessie**
I've spent hours and hours into looking what I was doing wrong till I take a look into the code and saw this potential issue here.
This code uses a variable `$s` which is uninitialised. As a consequence of this, the switch below will only execute the first case as `$s` will be 0 by default.
This causes the upgrading script to only convert the first batch of tables leaving all others empty which was exactly my issue.

In this PR I have removed this (possibly left over?) variable `$s` and its associated switch, the case bodies are placed one after the other so that all tables are converted.

### CODE REVIEW

**Comment by partydragen** [comment]
With the current information we gonna fix the switch, not remove it

**Comment by samerton** [comment]
@partydragen is this something you've looked into?

**Comment by partydragen** [comment]
> @partydragen is this something you've looked into?

Not much, No idea how we gonna do it better you do it i still need to learn more about ajax/js etc must run the steps links somehow

**Comment by Aberdeener** [comment]
@partydragen should this be closed/set as draft for the time being?

**Comment by partydragen** [comment]
> @partydragen should this be closed/set as draft for the time being?

Believe we can close it then have a issue for it?

**Pull request closed without merging**
