### PR TITLE
Change tachometer function slightly

### PR DESCRIPTION
**Pull request by PugaBear**
It was annoying me that the tachometer was clickable, so I was messing with it to make it not clickable but still show up correctly (cause if you remove href alltogher, the tachometer decides it doesnt wanna be in the right place anymore). I honestly came across this solution by accident when I typo'd, but hey, it works. Idk if its valid though. Feel free to send this to the trash can. Just something I liked having.

### CODE REVIEW

**Comment by samerton** [comment]
Thanks for this, however I don't think href"" in terms of HTML formatting is the best answer.

I've taken a quick look, and removing the href attribute altogether (so the tag is `<a data-toggle="tooltip" id="page_load_tooltip" title="Page loading..">`  seems to work okay. Could you try this again to confirm, and then I'll alter the code accordingly?

**Comment by PugaBear** [comment]
Huh, okay, I really thought removing href broke it. Maybe I did something else. That works too

**Comment by PugaBear** [comment]
I duplicated what I remember by removing the a tag alltogether. I have no idea why I did that in the first place- It was probably 3am.

**Comment by samerton** [comment]
Thanks :)

**Pull request merged**
