### PR TITLE
Big update

### PR DESCRIPTION
**Pull request by jesseke55**
Due the reason that you didn`t add a credits page so I decided to make this for you :)

### CODE REVIEW

**Comment by jesseke55** [comment]
Feel free if you want to add more information :D

**Comment by Ariuw** [comment]
I am not in the Spanish Translation Team :(

**Comment by samerton** [comment]
Thanks for this, however instead of the page being a custom page (which would be configurable through the AdminCP), I'd probably rework this so it's a normal page (from within the pages folder).

@Ariuw Oops, sorry about that, I'll add you now :)

**Comment by samerton** [comment]
Just another thought, if a contributor list is added (such as the one within this pull request, or potentially on the Wiki), the credits link could point to this instead of it being bundled within Nameless itself.

**Pull request closed without merging**
